name: GitLeaks Secret Scan

on:
  push:
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Rodar GitLeaks
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true 
          redact: true
