name: GitLeaks Secret Scan

on:
  push:
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Rodar GitLeaks
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true # O pipeline falha se encontrar um segredo
          redact: true # Esconde o segredo nos logs para segurança
